FROM ubuntu:25.10

RUN apt-get update
RUN apt-get -y install locales
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

RUN apt-get install -y --no-install-recommends openjdk-21-jre-headless ffmpeg ffmpegthumbnailer
RUN rm -rf /var/lib/apt/lists/* 

ENV LANG=en_US.UTF-8 
ENV LANGUAGE=en_US:en 
ENV LC_ALL=en_US.UTF-8

