version: '3.1'
services:
  database:
    image: 'mariadb:11'
    environment:
      - MARIADB_DATABASE=raspadmin
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - './mysql:/var/lib/mysql'

  backend:
    image: 'mundotv789123/raspadmin:java'
    ports:
      - '8080:8080'
    volumes:
      - './files:/app/files'
      - type: bind
        source: ./application.properties
        target: /app/application.properties
    environment:
      - MYSQL_HOST=database
      - MYSQL_DB=raspadmin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    depends_on:
      - database

