name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  DOCKER_IMAGE_TAG: mundotv789123/raspadmin:java
  DOCKER_USERNAME: mundotv789123

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up environment docker tag
        id: set_env
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "DOCKER_IMAGE_TAG=${{ env.DOCKER_IMAGE_TAG }}-dev" >> $GITHUB_ENV
          fi

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project with Maven
        run: mvn package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.DOCKER_IMAGE_TAG }}"
          platforms: linux/amd64,linux/arm64
