name: Docker Image CI Base

env:
  DOCKER_IMAGE_TAG: mundotv789123/raspadmin:java
  DOCKER_USERNAME: mundotv789123

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.base
          context: .
          push: true
          tags: mundotv789123/raspadmin:base
          platforms: linux/amd64,linux/arm64
